### ISSUE TITLE
Reading from postgres returns data not in time-sorted order

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-postgres-adapter#10]
This is a blocker bug for me. When I read from a postgres table, data comes back ordered by something that isn't time (I cannot tell if there is any order), resulting in RT-BATCH-OUT-OF-ORDER "Warning: batch dropped out-of-order point(s)" errors in the downstream juttle. 

This is how I ingest the data. The `time` field is configured to be of type `timestamp` (also tried with `text` with the same results):

```
juttle> read postgres -raw 'CREATE TABLE kb_timestamped(name text,host text,time timestamp,kb_out double precision);'
juttle> read file -format 'jsonl' -file '/Users/dmehra/git/scratch/vlad/jut-sql-demo/rawdata/kbs_metrics_sorted.json' | write postgres -table 'kb_timestamped'
```

Fwiw my input file is time-sorted; originally it wasn't, and I thought that may be the problem, so I pre-sorted it by time before ingesting. 

My data covers 24 hours from `Sat Feb 22 21:52:35 UTC 2014` (epoch seconds 1393105955) to `Sun Feb 23 21:52:35 UTC 2014` (epoch seconds 1393192355). There are a total 2574279 points, and they all get ingested into postgres; juttle `reduce count()` matches this number.

I can see that reads are not returning properly sorted data because, for example, the last point is not what I know it to be from the input file:

```
{"name":"app.ep.client_http.kbytes_out","host":"host1012.joffrey.jutt.le","time":1393192355000,"kb_out":98982.8359375}
```

In juttle I only get this point if I explicitly limit the time range to its exact second; with simple `tail 1` I get some other point which is hours earlier:

```
juttle> read postgres -table "kb_timestamped" -from :2014-02-23T21:52:35: -to :2014-02-23T21:52:36: | tail 1
┌────────────────────────────────────┬────────────────────────────────────────────┬──────────────────────────────┬────────────────────┐
│ time                               │ name                                       │ host                         │ kb_out             │
├────────────────────────────────────┼────────────────────────────────────────────┼──────────────────────────────┼────────────────────┤
│ 2014-02-23T21:52:35.000Z           │ app.ep.client_http.kbytes_out              │ host1012.joffrey.jutt.le         │ 98982.8359375      │
└────────────────────────────────────┴────────────────────────────────────────────┴──────────────────────────────┴────────────────────┘

juttle> read postgres -table "kb_timestamped" | tail 1
┌────────────────────────────────────┬────────────────────────────────────────────┬─────────────────────────────┬─────────────────┐
│ time                               │ name                                       │ host                        │ kb_out          │
├────────────────────────────────────┼────────────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ 2014-02-23T15:55:57.000Z           │ app.ep.client_http.kbytes_out              │ host949.jeyne.jutt.le         │ 58532.90625     │
└────────────────────────────────────┴────────────────────────────────────────────┴─────────────────────────────┴─────────────────┘

```

This is the juttle that results in a chart with OUT-OF-ORDER error, and time boundaries that do not cover a full day like they should:

```
read postgres -table 'kb_timestamped'
| keep host, time, kb_out
| reduce -every :10m: count()
| view timechart -title 'Point counts'
```

![image](https://cloud.githubusercontent.com/assets/5817365/12535037/2b627d08-c22a-11e5-87e7-57454bb216d2.png)

**Comment by VladVega** [comment]
The quick solution currently is to set the `timeField` option to the column name here. The next step is to change the logic in the Juttle adapter base class to infer timeField and sorting in some cases.

**Comment by dmehra** [comment]
Thank you, the quick solution works for me, this returns data in time-sorted order:

```
read postgres -table 'kb_timestamped' -timeField 'time'
```

The above works with or without specifying -from/-to. However specifying only -from/-to without -timeField returns data unsorted, I assume the coming fix will cover that case.

**Comment by VladVega** [comment]
For now does it makes sense to add to the docs that if `timeField` specified then data sorted by time?

**Comment by dmehra** [comment]
Yes, let's document that you're required to pass -timeField to the read to get time sorting, and then update the docs when the real fix comes in.

**Comment by VladVega** [comment]
@dmehra I just tried this query => all the points are now in time order. I believe this is fixed. Did you want to test before I close this issue?
