### ISSUE TITLE
Numeric values become strings on unoptimized reduce

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-postgres-adapter#7]
I'm ingesting metrics into a postgres table using juttle. The value field 'kb_out' is numeric, configured as decimal in the create table sql statement. However when I read the data back via juttle, these values come back as strings if my reduce is not optimized. To put it simpler, a plain read from postgres puts the values into the juttle pipeline as strings, instead of numbers.

My input file has numbers unquoted:

```
{
        "name": "app.ep.client_http.kbytes_out",
        "host": "host329.asha.jutt.le",
        "time": "2014-02-22T21:54:23.000Z",
        "kb_out": 61269.61328125
    },
```

This is the sql used (via juttle) to create the table:

```
read postgres -raw "CREATE TABLE kb_out(name text,host text,time text,kb_out decimal);"
```

This is the juttle to load the data:

```
read file -format "json" -file "/kbs_metrics.json" | write postgres -table "kb_out"
```

And this is the juttle to read back. It looks like one path (optimized) does the right thing, treating the value as a number, but the other (unoptimized) path does not:

```
juttle> read postgres -table "kb_out" | reduce avg(kb_out)
┌──────────────────────────┐
│ avg                      │
├──────────────────────────┤
│ 32131.18461922148        │
└──────────────────────────┘
juttle> read postgres -table "kb_out" | put kb = kb_out | reduce avg(kb)
┌──────────┐
│ avg      │
├──────────┤
│ NaN      │
└──────────┘
juttle> read postgres -table "kb_out" | put kb = Number.fromString(kb_out) | reduce avg(kb)
┌───────────────────────────┐
│ avg                       │
├───────────────────────────┤
│ 32131.184619221163        │
└───────────────────────────┘
juttle> read postgres -table "kb_out" | head 2 |view text
[
{"name":"app.ep.client_http.kbytes_out","host":"host329.asha.jutt.le","time":"2014-02-22T21:54:23.000Z","kb_out":"61269.61328125"},
{"name":"app.ep.client_http.kbytes_out","host":"host329.asha.jutt.le","time":"2014-02-22T21:59:23.000Z","kb_out":"56624.125"}
]
```

Notice how the values are quoted above, as strings, when they should be bare, as numbers.

**Comment by VladVega** [comment]
I've narrowed this down a bit - It's the `decimal` type that results in a string when using `knex` to query the sql db. 

`knex` does this so as not to lose precision: you'll find that the `decimal` type has a variable size (http://www.postgresql.org/docs/9.4/static/datatype-numeric.html). If that size becomes too large for javascript numbers (64bit float http://www.w3schools.com/js/js_numbers.asp) then the output number will lose precision. Represented as a string in Javascript it won't lose any precision. 

You'll notice that `double` in the above example will give you the expected result.

**Comment by dmehra** [comment]
Confirmed that creating a table with `double precision` or `real` type returns back numeric values. However, it didn't work for type `numeric` with specified precision, i tried `numeric (25,12)` but the values come back as strings from read. Shall we turn this into a documentation ticket, to spell out which types we support for numeric fields?

**Comment by VladVega** [comment]
This looks really good. Squashing and merging.

**Comment by VladVega** [comment]
Documented with pr #8
