### ISSUE TITLE
Document the connection string format

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-postgres-adapter#9]
Please document the components of the connection string in the README, it was not easy to figure out. The example has `postgres` in three places:

```
"connection": "postgres://postgres@localhost:5432/postgres"
```

and the [linked documentation](http://knexjs.org/#Installation-client) doesn't describe it in this way, but rather broken up as a JSON object with key/value pairs, so it's still not clear what order is expected in the config string. 

[Elsewhere](https://www.npmjs.com/package/pg-connection-string) i found this:

```
'postgres://someuser:somepassword@somehost:381/sometable'
```

but it doesn't seem right, as the final `postgres` in our connection string is not the name of a table. And it's unclear whether we'd accept the password in the string or not.  Let's include something like the above in the README, but with correct wording.

**Comment by VladVega** [comment]
Dcoumentation changes in pr: #12
